py_binary (
  name = "estimateResistanceUsingLS",
  srcs = ["estimateResistanceUsingLS.py"],
)

py_binary (
  name = "estimateResUsingRLS",
  srcs = ["estimateResUsingRLS.py"],
)

py_binary (
  name = "uniformDist",
  srcs = ["uniformDist.py"],
)

py_binary (
  name = "2dGaussianPlay",
  srcs = ["2dGaussianPlay.py"],
)